# Generated by Django 3.0.1 on 2019-12-19 18:40

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('alquiler', 'Aquiler'), ('venta', 'Venta')], max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveIntegerField()),
                ('surface', models.PositiveIntegerField()),
                ('garage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=search.models.upload_image_path, verbose_name='Image')),
                ('estate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='search.Estate')),
            ],
        ),
    ]
