# Generated by Django 3.0.1 on 2020-02-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='bathroom',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
